- .vscodeignore
First of all, thanks for this great extension!      
The Stimulus LSP wouldn't worked for me when installing the package through the VS Code extensions marketplace.   
Running the extension locally worked just fine.   
After some debugging I found the following error message in the VS Code developer tools:   
(I get the error message directly after installing or after opening a *.html.erb file for the first time)     
I had to add 4 npm dependencies to `.vscodeignore` before it worked for me.   
I'm not 100% sure if this is the right way...
> Add missing npm package dependencies to `.vscodeignore`

- server/src/diagnostics.ts
- server/src/utils.ts
Fixes #29 
For a controller like:
```js
export default class extends Controller {
static values = {
frameId: String
}
}
```
It will now properly map the dasherized attribute `frame-id` to the camelized name `frameId` as it's seen it the controller. It now handles cases like:
```html
<div 
data-controller="form"
data-form-frame-id-value="string"
></div>
```
Including namespaced controller identifiers:
```html
<div 
data-controller="nested--form"
data-nested--form-frame-id-value="string"
></div>
```
> Fix diagnostics for camelized Stimulus Value names

- README.md
- server/src/diagnostics.ts
> Introduce `stimulus.attribute.mismatch` diagnostic for Stimulus Values

- server/package.json
- server/src/code_actions.ts
- server/src/commands.ts
- server/src/data_providers/stimulus_html_data_provider.ts
- server/src/server.ts
- server/src/service.ts
- server/src/settings.ts
- server/yarn.lock
This pull request adds support for handling multiple controller root folders. This is useful when a project has more than one folder where it defines Stimulus controllers.
Previously any controller which wasn't located in `app/javascript/controllers/` wouldn't be provided with the right identifier. For example a controller in `app/packs/controllers/test_controller.js` would have been provided as `app--packs--controllers--test` which obviously isn't right. This is now fixed and will be correctly provided as `test`.
The `stimulus-parser` now automatically detects these root folders and doesn't rely on the hard-coded `app/javascript/controllers/` folder.
Additionally the `stimulus.controller.create` Quick-Fix action now also accounts for multiple root folders. If the project has more than …
> Support for multiple controller root folders

- README.md
Now that `stimulus-lsp` has a config in `nvim-lspconfig`, instructions can be added how to use the LSP in neovim.
Not really sure where is the best place for these instructions though?
> Added install instructions for neovim.

- README.md
- server/src/diagnostics.ts
First attempt at #84 
It first does a check if the controller has any parsing errors, if so adds a new error to the `data-controller` field. It then also ignores all other errors, as they make no sense. See this screenshot, where the only error is the parsing error:
When I fix the controller to be parsable, you see it shows the actual errors again:
Let me know what you think! Especially on the naming of the internal methods and consts and on the error message itself.
> Add diagnostic when controller can't be parsed

- client/src/client.ts
- package.json
- server/package.json
- server/src/code_actions.ts
- server/src/data_providers/stimulus_html_data_provider.ts
- server/src/diagnostics.ts
- server/src/server.ts
- server/src/service.ts
- server/tsconfig.json
- server/types/typescript-eslint__typescript-estree/index.d.ts
- server/types/typescript-eslint__typescript-types/index.d.ts
- server/types/typescript-eslint__visitor-keys/index.d.ts
- server/yarn.lock
This pull request updates the `stimulus-parser` version to `0.1.1` to get the new improved features. 
The new version also enables the features implemented in the pull requests  #178, #183, #186, #187
> Upgrade `stimulus-parser` to `0.1.1`

- client/src/controller_tree_view.ts
- client/src/requests.ts
- server/src/requests.ts
- server/src/server.ts
This pull requests adds two new sections to the Tree View. 
The previous list is now under the `Registered` section. Additionally, we now show an `Unregistered` section that lists all the controllers the parser detected and that weren't registered on the application.
> Show unregistered controller identifiers in Tree View 

- README.md
- server/src/code_actions.ts
- server/src/commands.ts
- server/src/diagnostics.ts
- server/src/server.ts
This pull request implements the `stimulus.controller.action.update` code action to resolve the `stimulus.controller.action.invalid` diagnostic. This code action be used to replace the invalid controller action name with the did you mean suggested.
Resolves https://github.com/marcoroth/stimulus-lsp/issues/161
> Implement `stimulus.controller.action.update` code action

- server/src/code_actions.ts
This pull request changes the behavior so that the LSP doesn't provide the `stimulus.controller.update` code action for a `stimulus.controller.invalid` diagnostic if the `suggestion` is `null`.
| Before | After |
| --- | --- |
| ![CleanShot 2024-03-02 at 16 50 10](https://github.com/marcoroth/stimulus-lsp/assets/6411752/57cf6f8d-72c6-4348-88ca-3b8c4f727976) | ![CleanShot 2024-03-02 at 16 48 42](https://github.com/marcoroth/stimulus-lsp/assets/6411752/fbbf17a8-2566-47c2-9114-ef35b0640c3d) |
Resolves https://github.com/marcoroth/stimulus-lsp/issues/156
> Don't provide `stimulus.controller.update` action if suggestion is null

- README.md
- server/src/code_actions.ts
- server/src/commands.ts
- server/src/server.ts
- server/src/service.ts
- server/src/utils.ts
This pull request adds the `stimulus.controller.register` code action which can be used to resolve a `stimulus.controller.invalid` diagnostic. The code action is provided if the invalid identifier was recognized in one of the controller definitions in the project that weren't registered yet or if any of the installed node modules exposes a controller with such an identifier.
https://github.com/marcoroth/stimulus-lsp/assets/6411752/c740aa8d-735a-4947-b10c-ff240857ca3e
Resolves https://github.com/marcoroth/stimulus-lsp/issues/175
> Implement `stimulus.controller.register` code action

- client/src/controller_tree_view.ts
- client/src/requests.ts
- package.json
- server/src/code_actions.ts
- server/src/requests.ts
- server/src/requests/controller_definitions.ts
- server/src/service.ts
- server/src/utils.ts
This pull request adds a  `controllerDefinitions.registerControllerDefinition` command that also gets added to any unregistered controller item in the Tree View.
It uses the `stimulus.controller.register` code action introduced in #205 under the hood.
> Add `registerControllerDefinition` command to Tree View Items 

- server/src/diagnostics.ts
- server/src/service.ts
This pull request refactors the way how the errors of a `SourceFile` get populated as diagnostics.
> Refactor `SourceFile` errors to diagnostic population

- README.md
- server/src/diagnostics.ts
This pull request introduces the `stimulus.controller.value_definition.default_value.type_mismatch` diagnostic which will be added to any JavaScript/TypeScript file that doesn't have a matching default value type.
Resolves https://github.com/marcoroth/stimulus-lsp/issues/169
> Validate Default Value types in Value Definitions

- README.md
- server/src/diagnostics.ts
This pull requests adds the `stimulus.controller.value_definition.unknown_type` diagnostic. We show this diagnostic when the given type for a Stimulus value is none of the known types (`Array`, `Boolean`, `Number`, `Object` or `String`).
> Add diagnostics for Stimulus Value types

- README.md
- server/src/diagnostics.ts
This pull request adds the  `stimulus.package.deprecated.import` diagnostic which gets added to import declarations that use the deprecated `stimulus` or `@stimulus/webpack-helpers` package.
Resolves https://github.com/marcoroth/stimulus-lsp/issues/155
> Implement `stimulus.package.deprecated.import` diagnostic

- server/src/diagnostics.ts
part of #248 and initial setup for adding suggestions / code actions for https://github.com/marcoroth/stimulus-lsp/issues/213 
Based on https://github.com/marcoroth/stimulus-parser/pull/114 and https://github.com/marcoroth/stimulus-parser/pull/117.
Display diagnostic only on the offending type value instead of the whole value object.
> Improve range-accuracy on value definition diagnostics

- server/src/utils.ts
| **Before** | **After** |
| --- | --- |
| ![CleanShot 2024-05-16 at 13 56 45@2x](https://github.com/marcoroth/stimulus-lsp/assets/6411752/267e50e3-76c5-4c1a-9f5a-bddc47c490b3) | ![CleanShot 2024-05-16 at 13 57 09@2x](https://github.com/marcoroth/stimulus-lsp/assets/6411752/4c9ae608-e02e-446a-a84e-65f3084ec090) |
Fixes #281
> Don't include file extension when registering controllers

- README.md
- server/src/code_actions.ts
- server/src/commands.ts
- server/src/config.ts
- server/src/diagnostics.ts
- server/src/server.ts
- server/src/service.ts
- server/tsconfig.json
This pull request introduces a minimal `Config` object which allows to configure ignore-lists for controller identifiers and HTML attributes. 
The idea is that the `.stimulus-lsp/config.json` file is committed to the git repository so that ignored controllers and attributes are shared between all people the team.
https://github.com/marcoroth/stimulus-lsp/assets/6411752/2181b216-50fd-4c50-94fe-466109d3a035
Resolves https://github.com/marcoroth/stimulus-lsp/issues/75
> Introduce `Config` class to configure ignore-list

- server/src/commands.ts
Editors other than Visual Studio Code utilize the `file://` URI scheme for the `window.showDocument()` function which is used in the Stimulus Config Code Action Commands.
This pull request adds the `file://` scheme to the newly added Commands in #289.
Fixes https://github.com/marcoroth/stimulus-lsp/issues/75#issuecomment-2127903372 @christopher-b pointed out in #75.
> Add `file://` URI scheme to Stimulus Config Commands

- server/src/commands.ts
Hi. This pull request resolves the problem with the "createController" command in editors like Zed (https://github.com/zed-industries/zed/issues/18218).
According to the LSP specification, the "CreateFile" operation uses the `DocumentUri` type for the resource name:
```json
{
"kind": "create",
"uri": "file:///Users/file.js"
}
```
However, the "createController" command currently uses an absolute path, which breaks compatibility with
clients other than VSCode. To comply with the specification and make this feature working in other clients,
the command must use a URI in the "CreateFile" operation.
Stimulus LSP sends this response when you try to create the missing controller via available code actions:
```json
{
"jsonrpc": "2.0",
"id": 4,
"method": "workspace/applyEdit",
"params": {
"edit": …
```
> Use URI for "createController" command
